// subtitles.js

// 1. 단어별 배열 (요청한 타임 인덱스 기준)
const englishWords = [
  // 1. "My dad worked at a snack factory."
  { word: "My", start: 0.01 },
  { word: "dad", start: 0.13 },
  { word: "worked", start: 0.23 },
  { word: "at", start: 0.55 },
  { word: "a", start: 0.65 },
  { word: "snack", start: 0.71 },
  { word: "factory,", start: 0.9 },
  // 2. "So as his son, which was quite interesting,"
  { word: "so", start: 1.61 },
  { word: "as", start: 1.97 },
  { word: "his", start: 2.1 },
  { word: "son,", start: 2.24 },
  { word: "which", start: 2.79 },
  { word: "was", start: 3.0 },
  { word: "quite", start: 3.1 },
  { word: "interesting,", start: 3.31 },
  // 3. "as you might expect, exposed to snacks from a young age."
  { word: "as", start: 4.21 },
  { word: "you", start: 4.29 },
  { word: "might", start: 4.42 },
  { word: "expect,", start: 4.62 },
  { word: "exposed", start: 5.16 },
  { word: "to", start: 5.48 },
  { word: "snacks", start: 5.64 },
  { word: "from", start: 6.0 },
  { word: "a", start: 6.16 },
  { word: "young", start: 6.26 },
  { word: "age.", start: 6.44 },
  // 4. "I learned to cherish them."
  { word: "I", start: 7.32 },
  { word: "learned", start: 7.46 },
  { word: "to", start: 7.72 },
  { word: "cherish", start: 7.84 },
  { word: "them.", start: 8.02 },
  // 5. "I can't throw away crumbs, can't toss them."
  { word: "I", start: 9.06 },
  { word: "can't", start: 9.16 },
  { word: "throw", start: 9.46 },
  { word: "away", start: 9.7 },
  { word: "crumbs,", start: 9.98 },
  { word: "can't", start: 10.9 },
  { word: "toss", start: 11.02 },
  { word: "them.", start: 11.26 },
  // 6. "Even with bread, you know?"
  { word: "Even", start: 12.04 },
  { word: "with", start: 12.28 },
  { word: "bread,", start: 12.46 },
  { word: "you", start: 12.64 },
  { word: "know?", start: 12.74 },
  // 7. "I simply do this and toss it."
  { word: "I", start: 13.9 },
  { word: "simply", start: 14.05 },
  { word: "do", start: 14.22 },
  { word: "this", start: 14.38 },
  { word: "and", start: 14.74 },
  { word: "toss", start: 15.0 },
  { word: "it.", start: 15.25 },
  // 8. "It's hard to throw away these crumbs."
  { word: "It's", start: 16.23 },
  { word: "hard", start: 16.33 },
  { word: "to", start: 16.51 },
  { word: "throw", start: 16.61 },
  { word: "away", start: 16.85 },
  { word: "these", start: 17.05 },
  { word: "crumbs.", start: 17.27 },
  // 9. "But it certainly faced a tough opponent."
  { word: "But", start: 18.75 },
  { word: "it", start: 18.91 },
  { word: "certainly", start: 19.05 },
  { word: "faced", start: 19.55 },
  { word: "a", start: 19.91 },
  { word: "tough", start: 20.0 },
  { word: "opponent.", start: 20.33 },
  // 10. "Shouldn't we perhaps balance this out internally?"
  { word: "Shouldn't", start: 24.55 },
  { word: "we", start: 24.97 },
  { word: "perhaps", start: 25.19 },
  { word: "balance", start: 25.73 },
  { word: "this", start: 26.13 },
  { word: "out", start: 26.42 },
  { word: "internally?", start: 27.18 },
  // 11. "Balance it with a user patch."
  { word: "Balance", start: 27.96 },
  { word: "it", start: 28.36 },
  { word: "with", start: 28.48 },
  { word: "a", start: 28.66 },
  { word: "user", start: 28.88 },
  { word: "patch.", start: 29.2 },
  // 12. "It's actually a three-color pen,"
  { word: "It's", start: 33.65 },
  { word: "actually", start: 33.95 },
  { word: "a", start: 34.23 },
  { word: "three-color", start: 34.35 },
  { word: "pen,", start: 34.95 },
  // 13. "but unfortunately, two colors don't work, right?"
  { word: "but", start: 35.31 },
  { word: "unfortunately,", start: 35.83 },
  { word: "two", start: 37.05 },
  { word: "colors", start: 37.25 },
  { word: "don't", start: 37.59 },
  { word: "work,", start: 37.81 },
  { word: "right?", start: 38.69 },
  // 14. "Two colors aren't working."
  { word: "Two", start: 39.82 },
  { word: "colors", start: 40.13 },
  { word: "aren't", start: 40.44 },
  { word: "working.", start: 40.62 },
  // 15. "The color is kind of a bright,"
  { word: "The", start: 43.14 },
  { word: "color", start: 43.28 },
  { word: "is", start: 43.6 },
  { word: "kind", start: 43.7 },
  { word: "of", start: 44.06 },
  { word: "a", start: 44.12 },
  { word: "bright,", start: 44.26 },
  // 16. "almost neon-like fluorescent shade, you know?"
  { word: "almost", start: 44.9 },
  { word: "neon-like", start: 45.22 },
  { word: "fluorescent", start: 45.97 },
  { word: "shade,", start: 46.41 },
  { word: "you", start: 46.69 },
  { word: "know?", start: 46.81 },
  // 17. "Like lemon color."
  { word: "Like", start: 50.29 },
  { word: "lemon", start: 50.79 },
  { word: "color.", start: 51.05 },
  // 18. "Hard to see when drawing."
  { word: "Hard", start: 52.19 },
  { word: "to", start: 52.36 },
  { word: "see", start: 52.52 },
  { word: "when", start: 52.68 },
  { word: "drawing.", start: 52.84 },
  // 19. "You have to hold it up to the light to see it."
  { word: "You", start: 54.72 },
  { word: "have", start: 54.86 },
  { word: "to", start: 54.98 },
  { word: "hold", start: 55.08 },
  { word: "it", start: 55.26 },
  { word: "up", start: 55.38 },
  { word: "to", start: 55.48 },
  { word: "the", start: 55.6 },
  { word: "light", start: 55.72 },
  { word: "to", start: 55.82 },
  { word: "see", start: 55.96 },
  { word: "it.", start: 56.1 },
  // 20. "Let's just simply leave it at that."
  { word: "Let's", start: 56.92 },
  { word: "just", start: 57.14 },
  { word: "simply", start: 57.32 },
  { word: "leave", start: 57.72 },
  { word: "it", start: 57.94 },
  { word: "at", start: 58.08 },
  { word: "that.", start: 58.2 },
  // 21. "What's more regrettable?"
  { word: "What's", start: 62.72 },
  { word: "more", start: 62.94 },
  { word: "regrettable?", start: 63.13 },
  // 22. "Perhaps cracker crumbs, right?"
  { word: "Perhaps", start: 64.69 },
  { word: "cracker", start: 66.02 },
  { word: "crumbs,", start: 66.22 },
  { word: "right?", start: 66.65 },
  // 23. "Throwing away crumbs is indeed a sin."
  { word: "Throwing", start: 68.05 },
  { word: "away", start: 68.26 },
  { word: "crumbs", start: 68.46 },
  { word: "is", start: 68.68 },
  { word: "indeed", start: 68.84 },
  { word: "a", start: 69.04 },
  { word: "sin.", start: 69.24 },
];

// 2. 문장별 배열 (문장 단위 표출)
const englishSentences = [
  { start: 0.01, end: 1.47, text: "My dad worked at a snack factory." },
  {
    start: 1.61,
    end: 3.85,
    text: "So as his son, which was quite interesting,",
  },
  {
    start: 4.21,
    end: 6.82,
    text: "as you might expect, exposed to snacks from a young age.",
  },
  { start: 7.32, end: 8.4, text: "I learned to cherish them." },
  {
    start: 9.06,
    end: 11.9,
    text: "I can't throw away crumbs, can't toss them.",
  },
  {
    start: 12.04,
    end: 13.08,
    text: "Even with bread, you know?",
  },
  { start: 13.9, end: 15.56, text: "I simply do this and toss it." },
  {
    start: 16.23,
    end: 17.65,
    text: "It's hard to throw away these crumbs.",
  },
  {
    start: 18.75,
    end: 20.91,
    text: "But it certainly faced a tough opponent.",
  },
  {
    start: 24.55,
    end: 27.72,
    text: "Shouldn't we perhaps balance this out internally?",
  },
  { start: 27.96, end: 30.04, text: "Balance it with a user patch." },
  {
    start: 33.65,
    end: 35.16,
    text: "It's actually a three-color pen,",
  },
  {
    start: 35.31,
    end: 39.81,
    text: "but unfortunately, two colors don't work, right?",
  },
  { start: 39.82, end: 41.62, text: "Two colors aren't working." },
  {
    start: 43.14,
    end: 44.64,
    text: "The color is kind of a bright,",
  },
  {
    start: 44.9,
    end: 47.05,
    text: "almost neon-like fluorescent shade, you know?",
  },
  { start: 50.29, end: 51.53, text: "Like lemon color." },
  { start: 52.19, end: 53.4, text: "Hard to see when drawing." },
  {
    start: 54.72,
    end: 56.48,
    text: "You have to hold it up to the light to see it.",
  },
  { start: 56.92, end: 58.95, text: "Let's just simply leave it at that." },
  { start: 62.72, end: 63.69, text: "What's more regrettable?" },
  { start: 64.69, end: 67.07, text: "Perhaps cracker crumbs, right?" },
  {
    start: 68.05,
    end: 70.49,
    text: "Throwing away crumbs is indeed a sin.",
  },
];

// 3. 한글 자막
const koreanSubtitles = [
  {
    start: 0.01,
    end: 1.47,
    text: "아버지가 과자 공장에서 일을 하셨었어.",
    highlight: false,
  },
  {
    start: 1.61,
    end: 3.85,
    text: "그래서 아들인 나는, 꽤 재밌었던 게,",
    highlight: false,
  },
  {
    start: 4.21,
    end: 6.82,
    text: "예상되겠지만, 어릴 때부터 과자를 많이 접했어.",
    highlight: false,
  },
  {
    start: 7.32,
    end: 8.4,
    text: "과자를 소중히 여기게 됐어.",
    highlight: false,
  },
  {
    start: 9.06,
    end: 11.9,
    text: "나는 부스러기를 못 버려. 차마 못 버리겠어.",
    highlight: false,
  },
  {
    start: 12.04,
    end: 13.08,
    text: "심지어 빵 부스러기도 그래. 뭔지 알지?",
    highlight: false,
  },
  {
    start: 13.9,
    end: 15.56,
    text: "나는 그냥 이렇게 해서 먹어버려.",
    highlight: false,
  },
  {
    start: 16.23,
    end: 17.65,
    text: "부스러기를 버리는 게 쉬운 게 아니야.",
    highlight: false,
  },
  {
    start: 18.75,
    end: 20.91,
    text: "근데 어쩌다 강력한 상대를 만났어.",
    highlight: false,
  },
  {
    start: 24.55,
    end: 27.72,
    text: "안에서 좀 밸런스를 잡아줘야 하지 않나?",
    highlight: false,
  },
  {
    start: 27.96,
    end: 30.04,
    text: "사용자 패치로 밸런스를 잡는 것처럼.",
    highlight: false,
  },
  {
    start: 33.65,
    end: 35.16,
    text: "이건 사실 3색 볼펜인데,",
    highlight: false,
  },
  {
    start: 35.31,
    end: 39.81,
    text: "안타깝게도 두 가지 색은 안 나오는 거 맞지?",
    highlight: false,
  },
  { start: 39.82, end: 41.62, text: "두 가지 색은 안 나와.", highlight: false },
  {
    start: 43.14,
    end: 44.64,
    text: "나오는 색은 또 밝은,",
  },
  {
    start: 44.9,
    end: 47.05,
    text: "네온 같은 형광 빛의 밝은 색이야. 뭔지 알지?",
    highlight: false,
  },
  { start: 50.29, end: 51.53, text: "레몬 색 같은 거.", highlight: false },
  {
    start: 52.19,
    end: 53.4,
    text: "뭘 그리려고 해도 잘 안 보여.",
    highlight: false,
  },
  {
    start: 54.72,
    end: 56.48,
    text: "빛에 비춰봐야 겨우 보일 정도야.",
    highlight: false,
  },
  {
    start: 56.92,
    end: 58.95,
    text: "그냥 그러려니 하고 넘어가야지 뭐.",
    highlight: false,
  },
  { start: 62.72, end: 63.69, text: "더 아쉬운 건 뭘까?", highlight: false },
  {
    start: 64.69,
    end: 67.07,
    text: "아마도 과자 부스러기가 맞겠지?",
    highlight: false,
  },
  {
    start: 68.05,
    end: 70.49,
    text: "부스러기 버리는 건 진짜 그냥 죄야.",
    highlight: false,
  },
];

// 4. export 구조 변경
const subtitles = {
  en: englishWords,
  enSentences: englishSentences,
  ko: koreanSubtitles,
};

export default subtitles;
